### ISSUE TITLE
中文乱码

### ISSUE THREAD

**Issue by zerone0x** [rmb122/Delete-my-hisroy-in-tieba#14]
Traceback (most recent call last):
  File "/Users/sober/Downloads/Delete-my-hisroy-in-tieba-master/DeleteMyHistory.py", line 271, in <module>
    main()
  File "/Users/sober/Downloads/Delete-my-hisroy-in-tieba-master/DeleteMyHistory.py", line 226, in main
    thread_list = get_thread_list(sess, config["thread"]["start"], config["thread"]["end"])
  File "/Users/sober/Downloads/Delete-my-hisroy-in-tieba-master/DeleteMyHistory.py", line 44, in get_thread_list
    res = sess.get(url)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1296, in _send_request
    self.putheader(hdr, value)
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1228, in putheader
    values[i] = one_value.encode('latin-1')
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 1014-1015: ordinal not in range(256)

**Comment by rmb122** [comment]
这看上去是百度的问题, 目测是百度往cookie里面塞了乱七八糟的东西导致 urllib 炸了, 可以重新登录设置 cookie 后试试...

**Comment by chenthefool** [comment]
重新登陆更新cookie后问题解决了，厉害👍
