### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa6 in position 514: illegal multibyte sequence

### ISSUE THREAD

**Issue by lomirus** [rmb122/Delete-my-hisroy-in-tieba#36]
```
.\DeleteMyHistory.exe
```
```
Traceback (most recent call last):
  File "DeleteMyHistory.py", line 321, in <module>
  File "DeleteMyHistory.py", line 298, in main
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa6 in position 514: illegal multibyte sequence
[39144] Failed to execute script DeleteMyHistory
```

- OS: WIndows 11
- Version: 1.1.1

**Comment by rmb122** [comment]
https://github.com/rmb122/delete-my-history-in-tieba/blob/9cd31584bcb88386d35c18c2df48004f86725d88/DeleteMyHistory.py#L298
貌似是cookie里面有奇怪的字符，一般情况下内容应该是纯ascii的，可以试试把对应奇怪字符删掉？或者清cookie重新登录下看看

**Comment by lomirus** [comment]
重新试了一次，确实没报错了🤔
