### ISSUE TITLE
python3.5下 执行报错

### ISSUE THREAD

**Issue by Knight-ZXW** [rmb122/Delete-my-hisroy-in-tieba#5]
Traceback (most recent call last):
  File "/Users/hb/code/pyhtonproject/Delete-my-hisroy-in-tieba/DeleteMyHistory.py", line 254, in <module>
    main()
  File "/Users/hb/code/pyhtonproject/Delete-my-hisroy-in-tieba/DeleteMyHistory.py", line 218, in main
    threadList = getThreadList(sess, config["thread"]["start"], config["thread"]["end"])
  File "/Users/hb/code/pyhtonproject/Delete-my-hisroy-in-tieba/DeleteMyHistory.py", line 47, in getThreadList
    html = bs4.BeautifulSoup(res.text, "lxml")
  File "/Users/hb/code/art/ArtAppBackend/pyenv/lib/python3.5/site-packages/bs4/__init__.py", line 281, in __init__
    self._feed()
  File "/Users/hb/code/art/ArtAppBackend/pyenv/lib/python3.5/site-packages/bs4/__init__.py", line 342, in _feed
    self.builder.feed(self.markup)
  File "/Users/hb/code/art/ArtAppBackend/pyenv/lib/python3.5/site-packages/bs4/builder/_lxml.py", line 287, in feed
    self.parser.feed(markup)
  File "src/lxml/parser.pxi", line 1242, in lxml.etree._FeedParser.feed
  File "src/lxml/parser.pxi", line 1285, in lxml.etree._FeedParser.feed
  File "src/lxml/parser.pxi", line 855, in lxml.etree._BaseParser._getPushParserContext
  File "src/lxml/parser.pxi", line 872, in lxml.etree._BaseParser._createContext
  File "src/lxml/parsertarget.pxi", line 111, in lxml.etree._TargetParserContext._setTarget
  File "src/lxml/parsertarget.pxi", line 41, in lxml.etree._PythonSaxParserTarget.__cinit__
  File "/Users/hb/.pyenv/versions/stackless-3.5.4/lib/python3.5/inspect.py", line 1057, in getfullargspec
    def getfullargspec(func):
SystemError: error return without exception set

**Comment by rmb122** [comment]
Traceback 到 lxml 里面去了 0.0 换个 python 版本试试 感觉有点玄学
